const seedMovies = [
  {id:'m1',title:'The Last Horizon',year:2025,genre:'Sci-Fi',rating:8.7,poster:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=700&q=85',embed:'https://www.youtube.com/embed/8ugaeA-nMTc',description:'When the last city on Earth loses contact with the stars, one pilot takes a quiet ship beyond the horizon to find a way home.'},
  {id:'m2',title:'Midnight in Kyoto',year:2024,genre:'Drama',rating:8.2,poster:'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=700&q=85',embed:'https://www.youtube.com/embed/6ZfuNTqbHE8',description:'Two strangers share one unforgettable night wandering through Kyoto, carrying secrets neither expected to reveal.'},
  {id:'m3',title:'Neon Run',year:2025,genre:'Action',rating:8.5,poster:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=700&q=85',embed:'https://www.youtube.com/embed/EXeTwQWrcwY',description:'A courier with one night to cross a city of neon and rain discovers that the package is more dangerous than the people chasing it.'},
  {id:'m4',title:'Northbound',year:2023,genre:'Adventure',rating:7.9,poster:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=700&q=85',embed:'https://www.youtube.com/embed/zSWdZVtXT7E',description:'A young cartographer follows a missing expedition into a frozen wilderness where every map ends.'},
  {id:'m5',title:'House of Echoes',year:2024,genre:'Mystery',rating:8.1,poster:'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=700&q=85',embed:'https://www.youtube.com/embed/YoHD9XEInc0',description:'A sound engineer returns to her childhood home and begins recording a voice that should not exist.'},
  {id:'m6',title:'After the Rain',year:2022,genre:'Romance',rating:7.8,poster:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=700&q=85',embed:'https://www.youtube.com/embed/2Vv-BfVoq4g',description:'A photographer and a chef meet on the wettest day of the year and find a reason to stay in the same city.'},
  {id:'m7',title:'Signal Zero',year:2025,genre:'Thriller',rating:8.4,poster:'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?auto=format&fit=crop&w=700&q=85',embed:'https://www.youtube.com/embed/7wtfhZwyrcc',description:'A late-night radio host hears a distress signal from tomorrow and has one broadcast to stop a disaster.'},
  {id:'m8',title:'The Green Room',year:2023,genre:'Comedy',rating:7.6,poster:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=700&q=85',embed:'https://www.youtube.com/embed/6hB3S9bIaco',description:'A group of actors trapped backstage turns opening night into the funniest rescue mission in show business.'}
];
const key='cinebhai_movies';
const storedMovies=localStorage.getItem(key);
let movies=storedMovies?JSON.parse(storedMovies):seedMovies;
if(!storedMovies)localStorage.setItem(key,JSON.stringify(seedMovies));
const $=s=>document.querySelector(s);
const save=()=>localStorage.setItem(key,JSON.stringify(movies));
function renderMovies(list=movies){
  const grid=$('#movieGrid'), empty=$('#emptyState');
  grid.innerHTML=list.map(m=>`<article class="movie-card" data-id="${m.id}"><div class="poster-wrap"><img src="${m.poster}" alt="${m.title} poster" loading="lazy"><span class="rating">★ ${Number(m.rating).toFixed(1)}</span></div><div class="movie-info"><h3>${m.title}</h3><div class="movie-meta">${m.year} · ${m.genre}</div></div></article>`).join('');
  empty.classList.toggle('hidden',list.length>0); grid.classList.toggle('hidden',!list.length);
  grid.querySelectorAll('.movie-card').forEach(card=>card.addEventListener('click',()=>openMovie(card.dataset.id)));
}
function renderAdmin(){ $('#adminRows').innerHTML=movies.map(m=>`<tr><td><div class="table-movie"><img src="${m.poster}" alt=""><span>${m.title}</span></div></td><td>${m.year}</td><td>${m.genre}</td><td>★ ${Number(m.rating).toFixed(1)}</td><td class="row-actions"><button data-edit="${m.id}">Edit</button><button class="delete" data-delete="${m.id}">Delete</button></td></tr>`).join('');
  document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>fillForm(b.dataset.edit)));
  document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>{if(confirm('Delete this movie from CineBhai?')){movies=movies.filter(m=>m.id!==b.dataset.delete);save();renderMovies();renderAdmin();}}));
}
function openMovie(id){const m=movies.find(x=>x.id===id);if(!m)return;$('#modalTitle').textContent=m.title;$('#modalMeta').textContent=`${m.year} · ${m.genre} · ★ ${Number(m.rating).toFixed(1)}`;$('#modalDescription').textContent=m.description;$('#movieFrame').src=m.embed;$('#movieModal').classList.remove('hidden');document.body.style.overflow='hidden';}
function closeMovie(){ $('#movieModal').classList.add('hidden');$('#movieFrame').src='';document.body.style.overflow='';}
function fillForm(id){const m=movies.find(x=>x.id===id);if(!m)return;$('#movieId').value=m.id;['title','year','genre','rating','poster','embed','description'].forEach(k=>$('#'+k).value=m[k]);$('#saveMovie').textContent='Save changes';$('#cancelEdit').classList.remove('hidden');location.hash='admin';}
function resetForm(){ $('#movieForm').reset();$('#movieId').value='';$('#saveMovie').textContent='Add movie';$('#cancelEdit').classList.add('hidden');}
function setSearch(value){$('#searchInput').value=value;const q=value.trim().toLowerCase();renderMovies(q?movies.filter(m=>`${m.title} ${m.genre} ${m.year}`.toLowerCase().includes(q)):movies);}
$('#heroPoster').src=movies[0].poster;
renderMovies();renderAdmin();
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();setSearch($('#searchInput').value);location.hash='movies';});$('#searchInput').addEventListener('input',e=>setSearch(e.target.value));$('#clearSearch').addEventListener('click',()=>setSearch(''));$('#heroPlay').addEventListener('click',()=>location.hash='movies');$('#heroInfo').addEventListener('click',()=>location.hash='movies');$('#spotlightBtn').addEventListener('click',()=>location.hash='movies');$('#surpriseBtn').addEventListener('click',()=>openMovie(movies[Math.floor(Math.random()*movies.length)].id));$('#modalClose').addEventListener('click',closeMovie);$('#movieModal').addEventListener('click',e=>{if(e.target.id==='movieModal')closeMovie()});$('#modalPlay').addEventListener('click',()=>$('#movieFrame').scrollIntoView({behavior:'smooth'}));$('#cancelEdit').addEventListener('click',resetForm);
$('#movieForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#movieId').value||`m${Date.now()}`;const movie={id,title:$('#title').value.trim(),year:Number($('#year').value),genre:$('#genre').value.trim(),rating:Number($('#rating').value),poster:$('#poster').value.trim(),embed:$('#embed').value.trim(),description:$('#description').value.trim()};const existing=movies.findIndex(m=>m.id===id);if(existing>-1)movies[existing]=movie;else movies.unshift(movie);save();renderMovies();renderAdmin();resetForm();document.querySelector('#movies').scrollIntoView({behavior:'smooth'});});
document.querySelectorAll('.genre-chip').forEach(()=>{});
const genreNames=['Action','Drama','Sci-Fi','Thriller','Adventure','Romance','Comedy','Mystery'];$('#genres').innerHTML=genreNames.map(g=>`<button class="genre-chip" data-genre="${g}">${g}<span> →</span></button>`).join('');document.querySelectorAll('.genre-chip').forEach(b=>b.addEventListener('click',()=>{setSearch(b.dataset.genre);location.hash='movies';}));
$('#mobileToggle').addEventListener('click',()=>$('#mainNav').classList.toggle('open'));document.querySelectorAll('.nav-link').forEach(a=>a.addEventListener('click',()=>$('#mainNav').classList.remove('open')));
